from __future__ import annotations

DEFAULT_EMBED_COLOR = 0xE74C3C

PHASE_COLOR_WORK = 0xE74C3C
PHASE_COLOR_SHORT_BREAK = 0x2ECC71
PHASE_COLOR_LONG_BREAK = 0x3498DB
PHASE_COLOR_ENDED = 0x95A5A6

PROGRESS_BAR_LENGTH = 20
PROGRESS_BAR_FILLED = "█"
PROGRESS_BAR_EMPTY = "░"

DEFAULT_WORK_SECONDS = 25 * 60
DEFAULT_SHORT_BREAK_SECONDS = 5 * 60
DEFAULT_LONG_BREAK_SECONDS = 15 * 60
DEFAULT_LONG_BREAK_EVERY = 4
DEFAULT_TICK_SECONDS = 10
